### PR TITLE
[AUTOMATED] Update Version Pinning for Terraform to support 0.13

### PR DESCRIPTION
**Pull request by Gowiem**
## What

1. Update Version Pinning for Terraform to support 0.13

## Why

1. This is a relatively minor update that the CloudPosse module already likely supports.
1. This allows module consumers to not individually update our Terraform module to support Terraform 0.13.

### CODE REVIEW

**Comment by Gowiem** [comment]
Hm. Seems we're getting a `make` error: 

```
cd /__w/actions/actions/test/src/.gopath/src/terraform-aws-eks-fargate-profile && dep ensure
Solving failure: package k8s.io/klog/v2 does not exist within project k8s.io/klog
make: *** [Makefile:36: /__w/actions/actions/test/src/.gopath/src/terraform-aws-eks-fargate-profile/vendor] Error 1
```

@osterman have you seen that before?

**Comment by aknysh** [comment]
@Gowiem please rebase

**Review by jamengual — APPROVED** [review]

**Pull request merged**
